pipeline {
    agent {
        node {
            label 'docker-agent-python'
        }
    }

    stages {
        stage('Install dependencies') {
            steps {
                dir('small-project') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('small-project') {
                    sh 'pytest'
                }
            }
        }
    }
}
